name: nodejs app

on:
  push:
    branches:
      - main
      - prod

jobs:
  prepare:
    outputs:
      image_version: ${{ steps.set_version.outputs.version }}
    runs-on: ubuntu-latest
    steps:

      - name: check out
        uses: actions/checkout@v4

      - name: extract version
        run: |
          echo "VERSION=$(jq -r .version package.json)" >> "$GITHUB_ENV"

      - name: test the env var
        run: echo "${{ env.VERSION }}"

      - name: set and output the version
        id: set_version
        run: echo "version=$VERSION" >> $GITHUB_OUTPUT

  
  test_version:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: check for the version
        run: echo "version is :${{ needs.prepare.outputs.image_version }}"

  docker_build_and_push:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: check out
        uses: actions/checkout@v4
      
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: user/app:${{ needs.prepare.outputs.image_version }}

          
